kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      {{- include ".Values.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include ".Values.selectorLabels" . | nindent 8 }}
        {{- if .Values.features.enablePrometheusTargetAllocator }}
        integrations.middleware.io/prometheus: "true"
        {{- end }}
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: mw-daemonset-otel-config-volume
        configMap:
          name: mw-daemonset-otel-config
          items:
            - key: otel-config
              path: otel-config-daemonset.yaml
      # volume binding for log collection 
      {{- if .Values.features.enableHostMonitoring }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
      {{- end }}
      {{- if .Values.features.enableContainerMonitoring }}
      - name: runcontainerd
        hostPath:
          path: /run/containerd/containerd.sock
      # volume binding for log collection
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      {{- end }}
      containers:
        - args:
          - mw-agent
          - start
          - --otel-config-file
          - /app/otel-config-daemonset.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MW_TARGET
              value: {{ or .Values.global.mw.target .Values.mw.target | quote }}
            - name: MW_KUBE_CLUSTER_NAME
              value: {{ or .Values.global.clusterMetadata.name .Values.clusterMetadata.name | quote }}
            - name: MW_AGENT_GRPC_PORT
              value: {{ .Values.service.grpc.targetPort | quote }}
            - name: MW_AGENT_HTTP_PORT
              value: {{ .Values.service.http.targetPort | quote }}
            - name: MW_AGENT_FLUENT_PORT
              value: {{ .Values.service.fluent.targetPort | quote }}
            - name: MW_AGENT_INTERNAL_METRICS_PORT
              value: {{ .Values.mw.agentInternalMetricsPort | quote }}
            - name: MW_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: MW_DOCKER_ENDPOINT
              value: {{ .Values.mw.dockerEndpoint | quote }}
            - name: MW_AGENT_FEATURES_INFRA_MONITORING
              value: {{ .Values.mw.agentFeatures.infraMonitoring | quote }}
            - name: MW_AGENT_SELF_PROFILING
              value: {{ .Values.mw.selfProfiling | quote }}
            - name: MW_PROFILING_SERVER_URL
              value: {{ .Values.mw.profilingServerUrl | quote}}
            - name: MW_ENABLE_DATADOG_RECEIVER
              value: {{ .Values.mw.enableDatadogReceiver | quote }}
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- if .Values.mw.apiKeyFromExistingSecret.enabled }}
            - name: MW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mw.apiKeyFromExistingSecret.name }}
                  key: {{ .Values.mw.apiKeyFromExistingSecret.key }}
            {{- else }}
            - name: MW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: middleware-secret
                  key: api-key
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ or .Values.image.repository .Values.agentImage.repository }}:{{ or .Values.image.tag .Values.agentImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ or .Values.image.pullPolicy .Values.agentImage.pullPolicy }}
          name: {{ .Chart.Name }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            {{- if not .Values.features.enableHostMonitoring }}
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            {{- end }}
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: mw-daemonset-otel-config-volume
            mountPath: /app
          {{- if .Values.features.enableHostMonitoring }}
          - mountPath: /var/log
            name: varlog
            readOnly: true
          - mountPath: /etc/machine-id
            name: etcmachineid
            readOnly: true
          {{- end }}
          {{- if .Values.features.enableContainerMonitoring }}
          - mountPath: /run/containerd/containerd.sock
            name: runcontainerd
            readOnly: true
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          {{- end }}
      restartPolicy: Always
      {{- if .Values.priorityClass.create }}
      priorityClassName: {{ include "mw-kube-agent.priorityClassName" . }}
      {{- end }}
      serviceAccountName: {{ include "mw-kube-agent.serviceAccountName" . }}
