name: Update OTel Config
on:
  push:
    branches:
      - test-workflow
    paths:
      #- "**/*.yaml"
      - "charts/mw-kube-agent-v2/templates/configmap-deployment.yaml"
      - "charts/mw-kube-agent-v2/templates/configmap-daemonset.yaml"
permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config --global url."https://${{ secrets.TRIAL_VAL }}:@github.com/".insteadOf "https://github.com/"
        env:
          GHCR_TOKEN: ${{ secrets.TRIAL_VAL }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Generate new config
        run: |
          cd charts/mw-kube-agent-v2
          helm template my-release . -s templates/configmap-daemonset.yaml | yq '.data."otel-config"' > /tmp/new-daemonset-config.yaml
          helm template my-release . -s templates/configmap-deployment.yaml | yq '.data."otel-config"' > /tmp/new-deployment-config.yaml

      #   - name: Checkout target repository
      #     uses: actions/checkout@v4
      #     with:
      #       repository: middleware-labs/install.middleware.io
      #       path: target-repo
      #       token: ${{ secrets.TRIAL_VAL }}

      - name: Check Token Permissions
        run: |
          echo "${{ secrets.TRIAL_VAL }}"
          curl -H "Authorization: token ${{ secrets.TRIAL_VAL }}" \
            https://api.github.com/repos/middleware-labs/install.middleware.io

      - name: Create branch and update file
        env:
          GH_TOKEN: ${{ secrets.TRIAL_VAL }}
        run: |

          git config --global user.email "naman.jain@middleware.io"
          git config --global user.name "naman-jain-15"

          git clone https://.:${{ secrets.TRIAL_VAL }}@github.com/middleware-labs/install.middleware.io.git
          cd install.middleware.io



          # Create new branch
          BRANCH_NAME="update-otel-config-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME

          # Update the file
          cp /tmp/new-daemonset-config.yaml scripts/otel-config-daemonset.yaml
          cp /tmp/new-deployment-config.yaml scripts/otel-config-deployment.yaml

          # Set up remote with token
          #git remote remove origin || true
          #git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/middleware-labs/install.middleware.io.git"

          # Commit and push changes
          git add .
          git commit -m "Update OTel config from helm charts"

          #git push "https://${GH_TOKEN}@github.com/middleware-labs/install.middleware.io.git" $BRANCH_NAME
          #fatal: could not read Password for 'https://***@github.com': No such device or address

          git config credential.helper store
          echo "https://oauth2:${GH_TOKEN}@github.com" > ~/.git-credentials
          git push origin $BRANCH_NAME

          #git push -u origin $BRANCH_NAME

          # Store branch name for next step
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TRIAL_VAL }}
          branch: ${{ env.BRANCH_NAME }}
          base: master
          title: "Update OTel config from helm charts"
          body: |
            Automated PR to update OTel configuration.

            Changes triggered by updates to:
            - configmap-deployment.yaml
            - configmap-daemonset.yaml

            Please review the changes carefully before merging.
